---
deployment:
  tasks:
    - export DEPLOYPATH=/home/pranmzcs/public_html/
    - /bin/cp -R dist/. $DEPLOYPATH
    - /bin/mkdir -p $DEPLOYPATH/api
    - /bin/cp -R api/. $DEPLOYPATH/api/
    - /bin/mkdir -p $DEPLOYPATH/uploads
    - /bin/cp -R uploads/. $DEPLOYPATH/uploads/
